import { NativeModules, Platform } from 'react-native';

export type LanguageCode = 'en' | 'de' | 'es' | 'fr';

export const getDeviceLanguage = (): LanguageCode => {
  let locale: string = 'en';
  try {
    if (Platform.OS === 'ios') {
      const settings = NativeModules.SettingsManager?.settings;
      // settings.AppleLanguages can be undefined on some iOS configurations/simulators
      locale = settings?.AppleLanguages?.[0] || settings?.AppleLocale || 'en';
    } else if (Platform.OS === 'android') {
      locale = NativeModules.I18nManager?.localeIdentifier || 'en';
    }
  } catch (error) {
    console.log('Error detecting locale:', error);
  }

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return ['en', 'de', 'es', 'fr'].includes(lang) ? (lang as LanguageCode) : 'en';
};

// UI Translations
export const translations = {
  en: {
    welcome: 'Welcome to DeutschLernen!',
    onboardingTitle: 'German Grammar',
    onboardingSubtitle: 'From beginner A1 to expert C2, learn systematically with beautiful interactive lessons and quizzes.',
    onboardingStep1Title: 'Interactive Lessons',
    onboardingStep1Desc: 'Learn clear grammar rules translated into your preferred language with practical examples.',
    onboardingStep2Title: 'Practice & Reinforce',
    onboardingStep2Desc: 'Test your understanding right after each lesson with specialized dynamic quizzes.',
    onboardingStep3Title: 'Track Your Progress',
    onboardingStep3Desc: 'Unlock advanced levels (A1 to C2) and watch your vocabulary and grammar skills soar.',
    getStarted: 'Get Started',
    next: 'Next',
    skip: 'Skip',
    back: 'Back',
    dashboard: 'German Grammar',
    overallProgress: 'Overall Progress',
    accuracy: 'Quiz Accuracy',
    lessonsCompleted: 'Completed',
    quizScore: 'Quiz Score',
    startLesson: 'Start Lesson',
    startQuiz: 'Start Quiz',
    retakeQuiz: 'Retake Quiz',
    selectLanguage: 'Device Language',
    settings: 'Settings',
    close: 'Close',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    quizFinished: 'Quiz Finished!',
    score: 'Your Score',
    perfectScore: 'Perfect! Keep it up!',
    goodScore: 'Great job! Almost perfect!',
    lowScore: 'Keep practicing to master this topic!',
    finish: 'Finish',
    backToDashboard: 'Back to Dashboard',
    currentLevelLocked: 'Unlock this level by completing the previous levels!',
    explanation: 'Explanation',
    level: 'Level',
    howToUse: 'How to Use',
    resetProgress: 'Reset Progress',
    resetAlertTitle: 'Reset Progress?',
    resetAlertDesc: 'This will clear all your completed lessons and quiz scores. This action cannot be undone.',
    cancel: 'Cancel',
    reset: 'Reset',
    exampleLabel: 'Example',
    summary: 'Summary',
  },
  de: {
    welcome: 'Willkommen bei DeutschLernen!',
    onboardingTitle: 'Deutsche Grammatik',
    onboardingSubtitle: 'Vom Anfänger A1 zum Experten C2, lernen Sie systematisch mit schönen interaktiven Lektionen und Quizzes.',
    onboardingStep1Title: 'Interaktive Lektionen',
    onboardingStep1Desc: 'Lernen Sie klare Grammatikregeln, übersetzt in Ihre bevorzugte Sprache, mit praktischen Beispielen.',
    onboardingStep2Title: 'Üben & Festigen',
    onboardingStep2Desc: 'Testen Sie Ihr Verständnis direkt nach jeder Lektion mit spezialisierten dynamischen Quizzes.',
    onboardingStep3Title: 'Verfolgen Sie Ihren Fortschritt',
    onboardingStep3Desc: 'Schalten Sie fortgeschrittene Niveaus (A1 bis C2) frei und sehen Sie, wie Ihre Sprachkenntnisse wachsen.',
    getStarted: 'Loslegen',
    next: 'Weiter',
    skip: 'Überspringen',
    back: 'Zurück',
    dashboard: 'Deutsche Grammatik',
    overallProgress: 'Gesamtfortschritt',
    accuracy: 'Quiz-Genauigkeit',
    lessonsCompleted: 'Abgeschlossen',
    quizScore: 'Quiz-Ergebnis',
    startLesson: 'Lektion starten',
    startQuiz: 'Quiz starten',
    retakeQuiz: 'Quiz wiederholen',
    selectLanguage: 'Gerätesprache',
    settings: 'Einstellungen',
    close: 'Schließen',
    correct: 'Richtig!',
    incorrect: 'Falsch',
    quizFinished: 'Quiz beendet!',
    score: 'Ihr Ergebnis',
    perfectScore: 'Perfekt! Weiter so!',
    goodScore: 'Gute Arbeit! Fast perfekt!',
    lowScore: 'Üben Sie weiter, um dieses Thema zu meistern!',
    finish: 'Beenden',
    backToDashboard: 'Zurück zum Dashboard',
    currentLevelLocked: 'Schalten Sie diese Stufe frei, indem Sie die vorherigen Stufen abschließen!',
    explanation: 'Erklärung',
    level: 'Stufe',
    howToUse: 'Anleitung',
    resetProgress: 'Fortschritt zurücksetzen',
    resetAlertTitle: 'Fortschritt zurücksetzen?',
    resetAlertDesc: 'Dies löscht alle abgeschlossenen Lektionen und Quiz-Ergebnisse. Dies kann nicht rückgängig gemacht werden.',
    cancel: 'Abbrechen',
    reset: 'Zurücksetzen',
    exampleLabel: 'Beispiel',
    summary: 'Zusammenfassung',
  },
  es: {
    welcome: '¡Bienvenido a DeutschLernen!',
    onboardingTitle: 'Gramática Alemana',
    onboardingSubtitle: 'Desde principiante A1 hasta experto C2, aprende sistemáticamente con hermosas lecciones interactivas y cuestionarios.',
    onboardingStep1Title: 'Lecciones Interactivas',
    onboardingStep1Desc: 'Aprende reglas gramaticales claras traducidas a tu idioma preferido con ejemplos prácticos.',
    onboardingStep2Title: 'Practica y Refuerza',
    onboardingStep2Desc: 'Pon a prueba tu comprensión justo después de cada lección con cuestionarios dinámicos especializados.',
    onboardingStep3Title: 'Sigue Tu Progreso',
    onboardingStep3Desc: 'Desbloquea niveles avanzados (A1 a C2) y observa cómo se elevan tus habilidades gramaticales.',
    getStarted: 'Comenzar',
    next: 'Siguiente',
    skip: 'Omitir',
    back: 'Atrás',
    dashboard: 'Gramática Alemana',
    overallProgress: 'Progreso General',
    accuracy: 'Precisión de Quiz',
    lessonsCompleted: 'Completado',
    quizScore: 'Puntuación',
    startLesson: 'Iniciar Lección',
    startQuiz: 'Iniciar Cuestionario',
    retakeQuiz: 'Repetir Cuestionario',
    selectLanguage: 'Idioma del Dispositivo',
    settings: 'Ajustes',
    close: 'Cerrar',
    correct: '¡Correcto!',
    incorrect: 'Incorrecto',
    quizFinished: '¡Cuestionario Terminado!',
    score: 'Tu Puntuación',
    perfectScore: '¡Perfecto! ¡Sigue así!',
    goodScore: '¡Gran trabajo! ¡Casi perfecto!',
    lowScore: '¡Sigue practicando para dominar este tema!',
    finish: 'Terminar',
    backToDashboard: 'Volver al Dashboard',
    currentLevelLocked: '¡Desbloquea este nivel completando los niveles anteriores!',
    explanation: 'Explicación',
    level: 'Nivel',
    howToUse: 'Cómo usar',
    resetProgress: 'Reiniciar Progreso',
    resetAlertTitle: '¿Reiniciar progreso?',
    resetAlertDesc: 'Esto borrará todas tus lecciones completadas y puntuaciones de cuestionarios. Esta acción no se puede deshacer.',
    cancel: 'Cancelar',
    reset: 'Reiniciar',
    exampleLabel: 'Ejemplo',
    summary: 'Resumen',
  },
  fr: {
    welcome: 'Bienvenue sur DeutschLernen !',
    onboardingTitle: 'Grammaire Allemande',
    onboardingSubtitle: 'De débutant A1 à expert C2, apprenez systématiquement avec de belles leçons interactives et des quiz.',
    onboardingStep1Title: 'Leçons Interactives',
    onboardingStep1Desc: 'Apprenez des règles de grammaire claires traduites dans votre langue préférée avec des exemples pratiques.',
    onboardingStep2Title: 'Pratiquer & Renforcer',
    onboardingStep2Desc: 'Testez votre compréhension juste après chaque leçon avec des quiz dynamiques et spécialisés.',
    onboardingStep3Title: 'Suivez Votre Progression',
    onboardingStep3Desc: 'Débloquez des niveaux avancés (A1 à C2) et regardez vos compétences grammaticales s\'envoler.',
    getStarted: 'Commencer',
    next: 'Suivant',
    skip: 'Passer',
    back: 'Retour',
    dashboard: 'Grammaire Allemande',
    overallProgress: 'Progression Globale',
    accuracy: 'Précision du Quiz',
    lessonsCompleted: 'Complété',
    quizScore: 'Score du Quiz',
    startLesson: 'Commencer la leçon',
    startQuiz: 'Commencer le quiz',
    retakeQuiz: 'Refaire le quiz',
    selectLanguage: 'Langue de l\'appareil',
    settings: 'Paramètres',
    close: 'Fermer',
    correct: 'Correct !',
    incorrect: 'Incorrect',
    quizFinished: 'Quiz Terminé !',
    score: 'Votre Score',
    perfectScore: 'Parfait ! Continuez comme ça !',
    goodScore: 'Bon travail ! Presque parfait !',
    lowScore: 'Continuez à vous entraîner pour maîtriser ce sujet !',
    finish: 'Terminer',
    backToDashboard: 'Retour au tableau de bord',
    currentLevelLocked: 'Débloquez ce niveau en complétant les niveaux précédents !',
    explanation: 'Explication',
    level: 'Niveau',
    howToUse: 'Mode d\'emploi',
    resetProgress: 'Réinitialiser la progression',
    resetAlertTitle: 'Réinitialiser la progression ?',
    resetAlertDesc: 'Cela effacera toutes vos leçons complétées et vos scores de quiz. Cette action est irréversible.',
    cancel: 'Annuler',
    reset: 'Réinitialiser',
    exampleLabel: 'Exemple',
    summary: 'Résumé',
  }
};
